### ISSUE TITLE
A lot of TODOs in Any

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#1494]
https://docs.perl6.org/type/Any#method_kv

**Comment by Altai-man** [comment]
Some table to keep up things:

- [ ] sum -  https://github.com/rakudo/rakudo/blob/nom/src/core/Any.pm#L469 but `my $a; $a.sum;` throws an exception. ???
- [x] keys
- [ ] flatmap - `$a.flatmap;` throws `Cannot resolve caller flatmap(Any: );`. It seems it is not even here in the first place. Delete?
- [ ] roll - TBD
- [ ] pick - TBD
- [ ] head - throws `Cannot resolve caller`. Delete?
- [ ] tail - throws `Cannot resolve caller`. Delete?
- [ ] skip - TBD
- [ ] prepend - TBD
- [ ] unshift - TBD
- [ ] first - TBD
- [ ] unique - TBD
- [ ] repeated - TBD
- [ ] reduce - TBD
- [ ] permutations - TBD
- [ ] categorize - TBD
- [ ] classify - TBD
- [ ] produce - TBD
- [ ] rotor - TBD
- [ ] pairs - TBD
- [ ] antipairs - TBD
- [ ] kv - TBD
- [ ] tree - TBD
- [ ] nl-out - TBD
- [ ] invert - TBD
- [ ] combinations - TBD
- [ ] print-nl - TBD
- [ ] iterator - TBD
- [ ] grep - TBD
- [ ] match - TBD
- [ ] append - TBD
- [ ] join - TBD
- [ ] values - TBD
- [ ] collate - TBD
- [ ] batch - TBD
- [ ] cache - TBD

**Comment by Altai-man** [comment]
`head` and `tail` on Any should be removed, I guess, because they need `Any:D`, not `Any:U`.

**Comment by Altai-man** [comment]
`print-nl` is broken, so delete it for now(?). See http://colabti.org/irclogger/irclogger_log/perl6?date=2017-09-02#l1233

**Comment by AlexDaniel** [comment]
@Altai-man what's the current status of this?

**Comment by Altai-man** [comment]
@AlexDaniel, hi.

Well, I indeed did some small effort towards this issue closing, perhaps not too much though, but as for now the things are like that:
1)Unfortunately, right now I don't have enough time&knowledge to explain `Any` business...
2)...as seen in https://github.com/perl6/doc/issues/1731 - a nice catch, by the way.
3)Personally, I think that current state is a little bit better than a long sheet of `TODO`s(arguable), but this issue still needs a bit more free time to be resolved than I have right now.

As we have a separate issue(i.e. `Fix the docs`, not `Write at least something instead of TODO`), I have a feeling that this can be closed.

**Comment by AlexDaniel** [comment]
OK! Thanks!

Closing as you say.

**Comment by JJ** [comment]
I have added back rotor and others; batch was already there. But what was the rationale after eliminating them? They can now be used in Any:U on Any:D. Am I missing something?

**Comment by JJ** [comment]
sum is still missing.

**Comment by JJ** [comment]
Why were head and tail deleted?

**Comment by JJ** [comment]
Only `print-nl` to go, but it errors no matter what. An issue: rakudo/rakudo#2713 has been created. I'll leave this open until it's solved.

**Comment by coke** [comment]
Created a clean issue with just the one missing method in https://github.com/Raku/doc/issues/4191
