### ISSUE TITLE
Document Supply.throttle(:$vent-at)

### ISSUE THREAD

**Issue by coke** [Raku/doc#175]
```
11:54 < [Coke]> lizmat: what is Supply.throttle(:$vent-at) do? (needs docs for
                http://docs.perl6.org/type/Supply#method_throttle)
11:55 < [Coke]> *does
11:55 < lizmat> it gives the value at which any buffered messages are bled of
                to the bleed supply
11:55 < lizmat> *off
11:57 < [Coke]> "bleed" also doesn't appear anywhere in the Supply docs.
11:58 < [Coke]> nor "message"
11:58 < [Coke]> I'll open a doc ticket.
```

**Comment by moritz** [comment]
It now says:

> The :bleed named parameter optionally specifies a Supply that will receive any values that were either explicitly bled (with the bleed control message), or automatically bled (if there's a vent-at active).
> 
> The :vent-at named parameter indicates the number of values that may be buffered before any additional value will be routed to the :bleed Supply. Defaults to 0 if not specified (causing no automatic bleeding to happen). Only makes sense if a :bleed Supply has also been specified.

 @coke is that sufficient for you? If yes, please close this issue.

**Comment by coke** [comment]
Thanks, closing.

**Comment by JJ** [comment]
I'm reopening, since it's got several problems, starting by the fact that its definition does not compile and does not correspond to the multi it is now. There are a number of defaults involved that should also be mentioned.

https://github.com/rakudo/rakudo/blob/5c8c7324e64d1edef0a07515e52bde8c56663717/src/core.c/Supply-coercers.pm6#L828-L1018
