### ISSUE TITLE
Fix left sidebar in the "Language" page

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#2138]
## The problem
Whenever I'm reading the docs and reach a certain point, I need to do some scrolling if
I want to get back to the table of contents and jump to a certain section.

## Suggestions
Make the sidebar (table of contents) fixed so that it stays in place when scrolling the doc.

**Comment by zoffixznet** [comment]
> I need to do some scrolling

FWIW, you can also press "Home" button.

> Make the sidebar (table of contents) fixed

Is there a way to make it behave decently when the entire table of contents doesn't fit on the screen? How to scroll it if it stays fixed?

**Comment by cfa** [comment]
Related: pages without a table of contents (e.g. [this](https://docs.perl6.org/language/temporal)) currently occupy far more horizontal space than pages with toc entries (e.g. [that](https://docs.perl6.org/language/create-cli)).

We should probably render an empty toc div to ensure consistency of presentation?

**Comment by sdondley** [comment]
This is a must. Docs are a real pain to use. Even just a simple css "sticky" tag for the TOC would be a huge improvement.

**Comment by raiph** [comment]
[What is a css "sticky" property?](https://www.google.com/search?q=What+is+a+css+%22sticky%22+property%3F)

**Comment by Altai-man** [comment]
The whole site needs a re-design at this point, but the last attempt to do so was rejected by the community.

Since then a year has passed and nobody volunteered to contribute more time on this to make it happen. The original contributors don't have much time (and experience in some areas) to put into it due to life circumstances, and the young contributors were forcefully shooed away. Due to this, the docs project is maintained to some minimum degree, but I would not expect much from it.

**Comment by sdondley** [comment]
It makes an html element "stick" to a specific location on the screen when you scroll down the page. See demo here: https://philipwalton.github.io/polyfill/demos/position-sticky/

I use it on my site as well to more dramatic effect: https://climatechangechat.com/setting_up_lsp_nvim-lspconfig_and_perl_in_neovim.html

I took a quick look at the Raku doc site. The TOC is done in a float so it's not going to be quite so simple. Some changes to the structure of the html would need to happen. But it's not a huge task.

**Comment by patrickbkr** [comment]
@Altai-man Speaking about a year having passed. Would it be possible to set up the redesigned docs page on a more permanent URL to pass around / look at?

**Comment by Altai-man** [comment]
>Would it be possible to set up the redesigned docs page on a more permanent URL to pass around / look at?

I think so. The previous url http://raku-infra-fsn1-01.rakulang.site:10012/ is not responding anymore, but it's a dockerfile, so someone can bring it up. What for though?

**Comment by sdondley** [comment]
I gotta imagine there are existing website frameworks for code documentation. Seems like that would be a good route to take instead of reinventing the wheel. Then everyone could agree ahead of time what would work.

**Comment by Altai-man** [comment]
Hi, @JJ.

So to clarify your position: you think we need a new UI and new tooling to go forward. You also say a lot of work has to be done to wire it up with the tooling we have. To clarify the state of things, this was already done, in terms of content the new website was a complete drop-in replacement for the current one.

As for the tooling, current libs including Documentable and Pod::To::HTML, patched, were re-used, nothing was re-invented, and it worked fine.

If the new solution is "great" and the work is already done, what are the exact steps necessary for it to go live? Or what are the reasons for it not to?

@patrickbkr

>I do hope that at one point the wounds are healed enough to pick things up again

IMO it's not about the wounds, but about authority. IMO the community lacked (and still does) an authority to resolve the disput. I remember Zoffix left due to different people having different ideas about the language's name and again, lack of authority to decide, as the last straw.
The RSC we asked to resolve the disput, just relayed it to the same group of people who created it.
The problem solving repo is not about deciding what trade-off to take when there are controversial opinions.

Richard were super enthusiastic about his website, to the point of calling people names, so I stepped down for a while, thinking that with enough passion he would eventually make something better than what I did, something that does tick the boxes and resolves all the issues like this silly one with the sidebar. But a year has passed and disappointingly not enough damns were given to get any progress in area (both by him and by the other community members who did not bring it up until now). So it boiled down to a dog in the manger situation, you prevent others from solving issues, but also don't have an availability / life circumstances to resolve them themselves, welcome to stagnation and eternal limbo.

So far I've stopped contributing in any way when it became clear the environment makes it really difficult to make any improvements not related to the core software (think rakudo). The websites, advertisement, anything that should be top notch to attract more users.

**Comment by JJ** [comment]
> Hi, @JJ.
> 
> So to clarify your position: you think we need a new UI and new tooling to go forward. You also say a lot of work has to be done to wire it up with the tooling we have. To clarify the state of things, this was already done, in terms of content the new website was a complete drop-in replacement for the current one.

Well, pretty much, but let me see if I can word it a bit more precisely
* I don't have anything against current style, but clearly the one you proposed is much better, better thought out, and in general an improvement. But I'm referring to the style only.
* Tooling is holding out pretty well, all things considered. But we need a new highlighter, because the one we have now is crumbling in pieces. If syntax highlighting is written in Raku, double bonus.
* I'd love any new proposal and PRs coming in, and all of them will be carefully considered.

> If the new solution is "great" and the work is already done, what are the exact steps necessary for it to go live? Or what are the reasons for it not to?

Well, to actually put that solution in a way that can be used with current tooling. That would include mainly reworking the templates, I guess, although there are templates at many levels and some of them are baked in, so some tool reworking might be needed.

> 
> So far I've stopped contributing in any way when it became clear the environment makes it really difficult to make any improvements not related to the core software (think rakudo). The websites, advertisement, anything that should be top notch to attract more users.

It's a real pity. Your contributions are very valuable, and valued. But we need to find common ground, and a sustainable way forward.

**Comment by Altai-man** [comment]
>Well, to actually put that solution in a way that can be used with current tooling

Can you please point out how the tooling currently used (Pod6 being processed by Documentable and rendered with Pod::To::HTML, inserted into Mustache templates) differs from the one used by me (Pod6 being processed by Documentable and rendered with Pod::To::HTML, inserted into Cro::WebApp templates (2x faster compared to Mustache))?

If we can point out the exact bit that dissatisfies people we can discuss what to do with it, from a technical perspective.

**Comment by JJ** [comment]
Well, you pointed that out already. Documentable uses Mustache by default, it would need to be changed to Cro::WebApp. IIRC another problem is that yours is a dynamic solution, while the current solution is totally static (in fact, rendered as GitHub pages too). So to propose a way forward, if there was an easy way of translating Cro::WebApp templates to Mustache, it would be a drop-in replacement for current one.

**Comment by Altai-man** [comment]
@JJ

>Documentable uses Mustache by default, it would need to be changed to Cro::WebApp

What are the reasons to keep it this way? I know the pro of Cro::WebApp is that it is faster. What are the pros of keeping Mustache?

>IIRC another problem is that yours is a dynamic solution, while the current solution is totally static

You are right, but being dynamic is necessary to 1)keep track of all the redirects, 404 is a big no-no; 2)avoid a lot of hacks wrt special symbols like $SOLIDUS$$SOLIDUS$$SOLIDUS$ type of issues; 3)eventually get something done on the documentation versioning, which is a super huge hole we have right now.

A static version can still be rendered just fine, because the old tooling (Documentable, Pod::To::HTML) is still in place, so nothing treats its existence AFAIUI.

@sdondley 

>From an outsiders perspective, It's obvious to me something, somewhere in the decision making process is not working well. I have no idea who is to blame nor do I care, but I do care that the process seems to be broken.

Right on the spot!

>I can help try to give people a little kick in the ass when I think it's needed.

This is appreciated, thank you very much (not an irony).

**Comment by patrickbkr** [comment]
@JJ I hope for a fruitful continuation of this discussion. Is there a reason for the silence?

**Comment by JJ** [comment]
No reason. Any reason why you ask?

**Comment by patrickbkr** [comment]
I don't know much about the details of either the current doc website or the changes Altai-man made. From what I understand of the above dialog is, that you and Altai-man increased each others understanding of the tech stacks and what areas still need work / where the difficulties lie. Altai-mans last answer sounded promising. From what I understood the two  biggest concerns were that the changes changed the docs page from a static generator to dynamically generating pages and moved from Mustache to Cro::WebApp. If I understand Altai-man correctly there are good reasons for these two changes.

Now I wonder whether these two problems should be discussed further or if there are other problematic aspects to be discussed or what else the next step of going forward could be.

**Comment by JJ** [comment]
Well, we found common ground in that the style needs to be changed, as in we need new CSS to present everything, as well as a new highlighter for code, because the current one is irremediably obsolete. I fail to understand why we need to change the templating system, and then that that templating system needs to be one that forces us to change the current, simple, low maintenance static infrastructure, to a dynamic one. But what I fail to see even more is why we need all those changes to fix the left sidebar in the "Language" page, which is what this issue was about.

**Comment by patrickbkr** [comment]
> But what I fail to see even more is why we need all those changes to fix the left sidebar in the "Language" page, which is what this issue was about.
 
Right. Is there already a ticket for getting Altai-mans work merged where this (misplaced) discussion could be moved?

**Comment by Altai-man** [comment]
>I fail to understand why we need to change the templating system

Because Mustache is slower than the new one.

>and then that that templating system needs to be one that forces us to change the current, simple, low maintenance static infrastructure, to a dynamic one

The templating engine has nothing to do with dynamic vs static.

We need a dynamic website to:
1)Handle redirects easily and thus rescue all the broken links around the internet we created in the past (and keep creating).
2)Handle Raku special symbols in URLs easily instead of $SOLIDUS$ kind of URLs that are very fragile, look bogus etc.
3)In future, handle multiple versions of the docs just like any decent docs website does.

I have been screaming about that for some time and apparently nobody thinks this is important, maybe _I_ am the insane one surrounded by normal people. Those points are always kept aside as something completely irrelevant.

Maybe it boils down to the perception of the language? If you see Raku as a toy language with just 1 main version of the docs that changes all the time and URLs go 404 for whatever reason, then yes, the ad-hoc "let's make it work somehow even if it's not well thought out first and think about how well it scales later" approach is oki-doki I guess. If we want to have one less thing where Raku ecosystem is immature and ad-hoc, we cannot cling to the baby clothes forever because you personally are used to it.

**Comment by sdondley** [comment]
I'd recommend agreeing to one small, concrete step that can agreed to. Get that done, and then come up with the next step, etc. until it's done.
