### ISSUE TITLE
Standardize how to introduce implementation-dependent stuff

### ISSUE THREAD

**Issue by tisonkun** [Raku/doc#2213]
our documents are almost of Perl 6 spec.
on which implementation-dependent stuff, we could set a `Rakudo NOTE` paragraph for supplement.
i think it is time to standardize how these implementation-dependent stuff be introduced. in the current document, we might use parenthesis or just mix them into text. we need a elegant and scalable way to introduce those stuff, though.

ref #2212

**Comment by AlexDaniel** [comment]
Related ticket: #1486

**Comment by zoffixznet** [comment]
> ref #2212

Just a minor note:

* Some things are "globally" implementation-specific, such as `.perl` output, since the only requirement the language is for that output to be `.EVAL`able to an equivalent object. These things might be OK to mix into general text.
* Some things are implementation-specific to a specific implementation: for example, Rakudo implementation comes with `Telemetry` modules that aren't part of the language.

**Comment by TisonKun** [comment]
close as not a problem

**Comment by JJ** [comment]
@TisonKun OK; your issue, your call, but it's not theoretically impossible to add metadata to paragraphs or index terms; with the new documentation specification, it's even relatively simple to do it. It's also a *wishlist* item, so it's pretty much guaranteed to be ~ignored~given a low priority. So it's not really a big deal if it stays.

**Comment by TisonKun** [comment]
I close issues because I myself am not interested in it any more. Anyone can open another issue and refer to this to continue the discussion.

...

**Comment by TisonKun** [comment]
by "not a problem", I mean with the ongoing discussion we lost the context that "Perl 6 will have many implementation and thus Rakudo specific details are implementation-dependent", since we even want to "just name it Rakudo"

**Comment by tisonkun** [comment]
As https://github.com/rakudo/rakudo/issues/1222#issuecomment-346952020, close this one. Please file another to continue the discussion if any.
