### ISSUE TITLE
Lock::Async vs. Lock

### ISSUE THREAD

**Issue by zoffixznet** [Raku/doc#2440]
- What's the difference between `Lock::Async` and `Lock`?
- What are the benefits of one over the other?
- When should I use which?

I skimmed https://docs.perl6.org/type/Lock::Async and https://docs.perl6.org/type/Lock but did not find any hints as to answers to those questions

**Comment by jnthn** [comment]
Here's some answers; you're free to pick from them to enhance the docs.

> What's the difference between Lock::Async and Lock?

Both are mechanisms for mutual exclusion.

`Lock` is a traditional, kernel supported, reentrant mutex. It *really* blocks a `Thread` while it waits, but at least does so in a way where the OS knows not to schedule it. Condition variables can also be associated with the lock.

`Lock::Async` returns a `Promise` upon lock acquisition, and the `Promise` will be kept if the lock is available. When it is unlocked, then the `Promise` of the next thing that called `lock` will be kept, if any. Since it is possible to `await` a `Promise` in a non-blocking way on the threadpool, then it's possible to use such a lock without really blocking a `Thread` at any point. If it's not available, something else can be scheduled to run. The `Lock::Async` mechanism is *not* reentrant, there's no condition variables, etc.

> What are the benefits of one over the other?

`Lock` offers familiar behavior to those who have done multi-threaded programming before, mapping, for example, directly to the semantics of a pthreads mutex. It's reentrant and provides condition variables.

By contrast, `Lock::Async` builds on Perl 6's `Promise` and `await`, and so is working at a rather higher level. It is the mechanism behind the `Supply` concurrency model. Since it doesn't block a real thread, you can potentially have thousands of outstanding lock acquisitions. However, there's no support for recursive acquisition.

> When should I use which?

It's best not to be using either of them directly, if writing application-level code. Pick something higher level. I've probably got more application-level concurrent/parallel code than most Perl 6 language users, and the number of times I'm directly using `Lock` or `Lock::Async` is close to zero (of course, I've got modules doing lower-level things like `OO::Monitors` that use them). But in general:

* If you're doing low-level stuff (native bindings) and/or actually want to block real OS threads, use `Lock`.
* If you want a non-blocking mutual exclusion and don't need recursion and are running code on the Perl 6 thread pool, use `Lock::Async`
