### ISSUE TITLE
Is there a way to get rid of “Using Perl 6 official documentation” page?

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#2577]
Is there a way to make the documentation more obvious so that https://docs.perl6.org/language/intro becomes unneeded?

![xkcd #1343](https://imgs.xkcd.com/comics/manuals.png)

**Comment by JJ** [comment]
We could call it something else, like "Introduction" It's not a howto page, per se...

**Comment by Altai-man** [comment]
@AlexDaniel briefly looking at the page, it seems to me like it is possible to replace this page existence with a bit more intuitive menu at https://docs.perl6.org/language.html
I generally like how stuff is ordered right now(though my opinion is irrelevant as not novice's one), but maybe adding e.g. descriptions to sections will be helpful? Maybe some other hints(I am not a designer even in a bit)? E.g. we have "Fundamental topics", but it is unlikely a user feels immediately what can be found in this section.

Also, of course, it is a good practice to read _whole_ documentation _step by step_, but we likely should reflect a fact that documentation is often used as a reference to quickly look up some thing/topic, so better not to expect thoughtful and wholehearted reading of every page by every user.

**Comment by JJ** [comment]
I am not too fond of eliminating pages, which means we're eliminating an URL and potentially breaking links. The URL says `intro`. Any suggestion to improve the content of the page is welcome.

**Comment by finanalyst** [comment]
The page was written in response to activity by a Perl 6 user who is very active on the email list, but who doesn't seem to have read some of the important pages that help a newbie orient themselves.

The aim was to highlight the pages that were most important for understanding the others. For example, the first thing you find in a description of a function is its signature, but for someone new to Perl 6, signatures can be mystifying. So a very important page to read before looking for a function is a description of signatures. Another important distinction of Perl 6 (I think) is the difference between Classes and Roles. And so on.

Perhaps the name of the page is not so good.

**Comment by finanalyst** [comment]
After thinking about this some more, what is wrong with having an explanation about how to use the manual? 

Documentation has multiple levels, eg. reference, tutorials, examples. Also, a big document without a Table of Content is almost useless, and most big documents have an Index. Aren't tables of content and indicies tools for using the document?

**Comment by coke** [comment]
Regarding not wanting to abandon an existing URL - we can create redirects so the old URL goes somewhere.

**Comment by 2colours** [comment]
I agree that neither the whining, nor the user-blaming has any place in the documentation, and the whole intro page seems kind of ad-hoc. I'm afraid the real reason for that is indecisiveness. Confer https://github.com/Raku/doc/discussions/4167. `Type` is _mostly_ a reference and `Language` is _mostly_ an explanation/tutorial kind of part; however, I suppose our hands are so much tied at this point that nobody dares to explicitly set these goals and communicate them.

That being said, that seems obvious that the docs need a "manual" simply because there are multiple goals simultaneously. And there are multiple goals simultaneously because, well, none of us know better. It is what it is. The need for guidance is _genuine_, given the circumstances. To answer the question: **no**, there is no way to completely remove it but there **should be a way to improve it**.

**Comment by coke** [comment]
Removed the offending intro paragraph and cleaned up a few things. Please let me know if anything specific was missed from this convo, open a new ticket for any other changes.
