### ISSUE TITLE
Spin off Pod::Convenience

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2696]
## The problem

Same as other modules, #1937 and #2573 , this module is not documented, although it does include its own test (05-pod-convenience). It also includes extract-pod, which is actually done now with [Pod::Load](https://github.com/JJ/p6-pod-load) (and is not using now the precompilation store), thus does not need to save to file and get it back.

## Suggestions

That particular routine should probably be eliminated and superseded by the equivalent in Pod::Load, and the rest of the routines revised and (possibly) include it in one of the other spun-off modules or simple left there and be documented and tested. 
first-code-block, also, does not seem to be used anywhere outside the test. We would have to review the rest of the routines for actual usage...

**Comment by coke** [comment]
What's the URL for Pod::Load's repo?

**Comment by JJ** [comment]
Linked.

**Comment by antoniogamiz** [comment]
`Pod::Convenience` has already been spinned off in this [repo](https://github.com/antoniogamiz/Pod-Utilities). It will be published in a few moments (when the PR is accepted).

Before integrate it with this repo, `Pod::Load` needs to be used instead of `extract-ood` (that function has not been included). `extract-pod` is used in several places:

~~~
htmlify.p6:302:            my $pod = extract-pod($file.path);
htmlify.p6:879:        p2h(extract-pod('doc/HomePage.pod6'),
htmlify.p6:883:        p2h(extract-pod('doc/404.pod6'),
lib/Pod/Convenience.pm6:119:sub extract-pod(IO() $file) is export {
xt/camelia-invocations.t:37:    my @chunks = extract-pod($file.IO).contents;
xt/examples-compilation.t:129:    my @chunks = extract-pod($file).contents;
~~~

**Comment by antoniogamiz** [comment]
In addition, these two functions have been moved there:

- `recurse-until-str` => defined at https://github.com/perl6/doc/blob/30516acd3c1974b0a55dc8585d63869ca1ed7c40/htmlify.p6#L460
- `textify-guts` => defined at https://github.com/perl6/doc/blob/30516acd3c1974b0a55dc8585d63869ca1ed7c40/htmlify.p6#L526

**Comment by coke** [comment]
Pod-Utilities doesn't seem to contain "extract-pod", which is the only function that the remaining xt/ tests that use this module need.

**Comment by coke** [comment]
https://github.com/antoniogamiz/Pod-Utilities/issues/10

**Comment by coke** [comment]
coke/pod branch has a first pass to test once POD::U has extract-pod

**Comment by JJ** [comment]
extract-pod will become a wrapper for Pod::Load eventually. It's been superseded by it.

**Comment by coke** [comment]
Ping on this ticket. No movement on Pod-Utilities here since 2020. Is it still on the roadmap there?

**Comment by 2colours** [comment]
Is there any point in keeping this issue at all?

**Comment by coke** [comment]
No, closing.
