### ISSUE TITLE
deployment of docs.perl6.org

### ISSUE THREAD

**Issue by rba** [Raku/doc#2929]
1) How should we deploy docs.perl6.org?

On the server from @niner there is currently no docker installed.

So far I started the same way the "old" system was installed with creating a user for each site, and a webserver (yet used nginx instead of apache this time) is serving the page or proxying to whatever serving on localhost.

Btw. current Dockerfile serves using morbo, what is not the production ready config. I would rather prefer hypnotoad instead.

Or should we point docs.perl6.org to the github pages setup?

2) What's the prefered way to trigger to update? 
cron + update.sh?

**Comment by JJ** [comment]
Right now it's just a bunch of static pages. It's also installed in https://perl6docs.github.io. First approximation would be to mirror that site, since it pretty much has everything.
However, as long as we're at it we'd like to do this #2909 as well as introduce every improvement @antoniogamiz has brought to the table. 
Re: 2 Also, there should be a way to deploy it automatically when a push is done to master. Previously there was a cron job that checked the repo every 10 minutes, and downloaded and built the documentation. Something more push-like (as opposed to pull) like a push web hook would be much more convenient. It can be done just the way it did (in the previous permanent infrastructure), anyway, if it's too much trouble.

**Comment by rba** [comment]
If github pages are the prefered deployment, you can just add docs.perl6.org on github side as custom domain and on DNS side I add a CNAME record pointing to it. Should we try to do this? If you like to play first we can try the same with docs.p6c.org as a test?

**Comment by JJ** [comment]
Hi,

El sáb., 3 ago. 2019 a las 0:05, Roman Baumer (<notifications@github.com>)
escribió:

> If github pages are the prefered deployment, you can just add
> docs.perl6.org on github side as custom domain and on DNS side I add a
> CNAME record pointing to it. Should we try to do this? If you like to play
> first we can try the same with docs.p6c.org as a test?
>

OK. I can do that, starting with docs.p6c.org, just in case.

**Comment by rba** [comment]
docs.p6c.org changed on DNS side.


```
$ dig docs.p6c.org

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> docs.p6c.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23899
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;docs.p6c.org.                  IN      A

;; ANSWER SECTION:
docs.p6c.org.           300     IN      CNAME   perl6docs.github.io.
perl6docs.github.io.    3599    IN      A       185.199.108.153
perl6docs.github.io.    3599    IN      A       185.199.110.153
perl6docs.github.io.    3599    IN      A       185.199.109.153
perl6docs.github.io.    3599    IN      A       185.199.111.153

;; Query time: 188 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat Aug 03 07:18:27 UTC 2019
;; MSG SIZE  rcvd: 138
```

**Comment by JJ** [comment]
Deployed now at http://docs.p6c.org/ Please stress-test it for any bug that might be in the static-HTML only infrastructure.

**Comment by 2colours** [comment]
Seems like this issue isn't relevant anymore. Perhaps it could be closed.
