### ISSUE TITLE
Build.pm6 should probably be deleted

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3002]
## The problem

It's in the main directory, I'm not sure it's used.

## Suggestions

Check for hidden usage and delete it if it's no longer used.

**Comment by JJ** [comment]
It's used in p6doc, which is spun off...

**Comment by coke** [comment]
It's a part of the install process with zef. see #3206

**Comment by JJ** [comment]
Yep, but still, it's only used in p6doc, which is now in another repo. So probably should be removed.

**Comment by coke** [comment]
I need a pointer to how the install of docs from this repo is supposed to work with the now-separated p6doc tool, so I can figure out what's left for installation in this repo. My expectation was that we would still be installing these docs so that p6doc could find them, and there are other tickets in this repo for fixing the install process in general.

**Comment by coke** [comment]
The correct issue is: "Do we want to install the documentation" from this repo;

If yes, we'll update the Build.pm to address it. If not, we'll update it to error out if someone tries to do an install.

There are other issues tracking that question.
