### ISSUE TITLE
Page search function conflicts with browser search

### ISSUE THREAD

**Issue by x-qq** [Raku/doc#3025]
There is a strange issue related to page's search focus and the way it reacts to keypresses intended for browser's own search function.

Steps to reproduce:
1) Open https://docs.perl6.org/type/Range
2) press ctrl-f to open browser search menu
3) enter main into browser search menu
4) press F3 F3 F3 to navigate to fourth match
5) press esc to close browse search bar

Expected behavior:
* browser search bar is closed, allowing me to read the search results

Actual behavior:
* browser search bar is closed
* browser viewport is shifted to the top of the page
* browser focus is placed inside page's own search bar
* I can no longer see my search result

Browser is chromium 76.0.3809.100 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)

**Comment by JJ** [comment]
It also happens with Firefox. We need to do something about focus. Thanks for the report.

**Comment by randyl** [comment]
This is a regression of https://github.com/Raku/doc/issues/1078. That issue was fixed in https://github.com/Raku/doc/commit/81f6ddc233c85917957220f1884277c3ace414dd by only focusing the page's search bar when at the top of the page. The commit used `$('body').scrollTop() == 0` to detect when the browser was at the top.

It seems like that logic no longer works on Chrome or Firefox for docs.raku.org. Several answers on stackoverflow.com suggested using window, document, or 'body' instead. Trying them in the Chrome console shows each one works, while 'body' doesn't:
```
$(window).scrollTop()
2312.727294921875

$(document).scrollTop()
2312.727294921875

$('html').scrollTop()
2312.727294921875

$('body').scrollTop()
0
```
I don't have enough expertise to know if one of these is more friendly across browsers.

**Comment by JJ** [comment]
Thanks. We'll try to fix this ASAP.

**Comment by coke** [comment]
There is a entirely new version of the website, created by https://github.com/Raku/doc/website. I'm pretty sure this issue has been resolved, but if you're still having issues, please open a fresh ticket on that site!
