### ISSUE TITLE
"link to everything on one page" leads to an error

### ISSUE THREAD

**Issue by cinch** [Raku/doc#3041]
## The problem

visit https://docs.perl6.org/ and click on "view everything in one file".
this leads to https://docs.perl6.org/perl6.html which spits out a mojollicious error page (Page not found... yet!).

**Comment by cinch** [comment]
![Screenshot_2019-09-28 Page not found (development mode)](https://user-images.githubusercontent.com/61357/65819519-2386cd80-e20d-11e9-8d3b-8d940f9b1d5a.png)

**Comment by AlexDaniel** [comment]
Ping @rba ?

**Comment by JJ** [comment]
Thanks for letting me know. I'll put it back there.

**Comment by JJ** [comment]
Not so trivial. We need to change the generation of a single page, which is using the old infrastructure. I'll try and get one somewhere and patch it there, but we'll need to fix that pronto.

**Comment by momozor** [comment]
@JJ 
Hi. Is there anyway I can help with this?

**Comment by JJ** [comment]
@momozor well, it's a problem with pod2onebigpage. It was using the files generated in the `build` directory, which are no longer used. In a first approximation, we could revert the changes made last year to using directly the sources, instead of those generated files that are no longer generated. In the longer run, however, it should use Pod::To::Cached, so if the first proves tricky, it might be better to just skip that and go directly to adapting module.

**Comment by coke** [comment]
perl6.html is still there on the current site, not erroring out at the moment, the first link you mentioned is no longer there, and this whole page will be replace after raku/doc-website goes live with an epub document instead.
