### ISSUE TITLE
Document $*W

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3050]
## The problem

It's a *very* specific variable, used extensibly in the MOP, but also [in the wild in the `if`module](https://github.com/FROGGS/p6-if/blob/master/lib/if.pm)

## Suggestions

Try and find what it does, and how it could be put to good use in creating interesting stuff like `if`

**Comment by jnthn** [comment]
I'd rather this wasn't documented. It's very much a Rakudo-internal thing, and even there it probably won't survive (the same forces act on it as with `$*ACTIONS`, which already went away).

**Comment by jnthn** [comment]
Ah, and as to what it does: it's the compilers *internal* model of declarations. It has a load of methods. None of them are considered a supported API, and they may be changed at any time (and have in the past).

**Comment by JJ** [comment]
The problem is when we find instances of it in the wild. Documentation
should be used to give developers a chance to create stuff, but also to
understand what has already been published, in this case p6-if, which is an
amazing piece of code, and it's relied on by several other modules in the
ecosystem.
So this is partly about not giving people who are working in the core an
unfair advantage (but it could be), but mainly about making perl6/doc a
real reference for the Perl 6 code that is out there. Even if it's got to
be surrounded by all kinds of caveats.

**Comment by JJ** [comment]
Please note that I'm not saying we should document all Rakudo Internals.
Only those pieces that already out in the wild (and this one has been for a
very long time).

**Comment by jnthn** [comment]
> The problem is when we find instances of it in the wild.

Well, from the perspective of a Rakudo developer, the problem is the usage of an internal implementation detail in the wild. :-)

> So this is partly about not giving people who are working in the core an unfair advantage

Making it easier to use internal details puts us at an unfair *disadvantage*: we're expected to make Rakudo better without breaking the ecosystem, but are then losing degrees of freedom that are helpful for doing that.

> p6-if, which is an amazing piece of code, and it's relied on by several other modules in the ecosystem

What we really need is to provide a way for `p6-if` - which I agree is a wonderfully creative piece of work, even it depending on unsupported interfaces - to do its thing via an interface we're happy to support.

**Comment by JJ** [comment]
If internal implementation details are used in the wild, they are not so internal... And sometimes documenting them helps someone understand better other features that are not so internal. 
Point is: people are going to use what they see fit no matter what. Documenting internals might make marginally more likely that people use them, thus increasing the risk of core supporting features just slightly (because we are talking about supporting *more* stuff, since it's already in the open, it might have to be supported (or not) anyway), but it makes exponentially more likely that people understands Perl 6 better and then use it for their own purposes. Of course, as long as we give all necessary caveats so that who use it must be pretty sure of what she does.

**Comment by JJ** [comment]
> 
> What we really need is to provide a way for `p6-if` - which I agree is a wonderfully creative piece of work, even it depending on unsupported interfaces - to do its thing via an interface we're happy to support.

Also, if this is kinda of a trick-or-treat thing, or, said in another way, "give this internal an external (and supported) interface or we'll document it", I'm all in :-)

**Comment by AlexDaniel** [comment]
Uh: https://gist.github.com/Whateverable/ba725edf0cc5c164101106f52e9180c2

**Comment by vrurg** [comment]
Perhaps the only acceptable way of documenting it is to add a huge banner saying something like: "this doc is approximate, things change permanently. Refer to the source code for more details".

Basically, if the variable is just noted in the docs with the above mentioning, that'd already be sufficient as to my view.

**Comment by Kaiepi** [comment]
I don't exactly envy anyone that'd need to read the code for my `Type::EnumHOW` module at the moment because it relies on `$*W` in addition to nqp, and it's not something I can avoid because the module provides sugar for generating enums dynamically, and as part of that it needs to handle the same things the compiler does when declaring an enum. While nqp is documented as being an internal feature, it wouldn't be clear to anyone that hasn't worked on Rakudo before where `$*W` is coming from, what it even is, or why it doesn't exist when you try to use it at runtime.

I think `$*W` should be documented, but with a similar disclaimer to the one `use nqp` has ("use at your own risk"). I think it should more heavily discourage its use than that though, because while `$*W` is very powerful with what it allows you to do, it's also very easy to misuse and end up with bugs that are very easy to mistake for legitimate compiler bugs. This is less of an issue when using nqp. @jnthn has the right idea with the type of disclaimer it'd need.

**Comment by coke** [comment]
Based on my current understanding, once Raku AST is complete, this special variable will no longer be present.
