### ISSUE TITLE
Numbered lists (and its alias #) are not documented

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3053]
## The problem

[S26 mentions numbered lists](https://design.perl6.org/S26.html#Ordered_lists), and its alias using # 

I'm not sure it's implemented, although [there are some references to using it as a config option](https://github.com/rakudo/rakudo/blob/6b418fbea627a4ad822944ef0ee798b54d82aff8/docs/announce/2018.09.md)

## Suggestions

Create example pods, check out roast, and add whatever is missing. Using `:numbered` as a configuration option is also part of #2632

**Comment by finanalyst** [comment]
I have been working on this. I have made raku-pod-render, which is the basis for Collection, so that it respects the `=config` directive as per S26. 

My plan is to write a plugin for raku-pod-render that implements the numbered lists, and also numbered headings. I plan to use the HTML options for `ul` to allow for all sorts of numbering options. 

I do not think this functionality can be included in Pod::To::HTML

**Comment by coke** [comment]
If it's not part of Pod::To::HTML, then we don't have to document it in the core docs. Thanks.
