### ISSUE TITLE
LEAVE block skipped when die is called

### ISSUE THREAD

**Issue by p6rt** [Raku/doc#3148]
Migrated from [rt.perl.org#126459](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126459) (status was 'new')

Searchable as RT126459$

**Comment by lizmat** [comment]
This has nothing to do with `CATCH`: the issue can be golfed to:

    sub a() { LEAVE say "left"; exit 1 };
    a

I guess because technically the `exit` is a sub that is being called, that does the exiting magic, like calling all `END` blocks, but it never returns, thus never leaving the block in which it was called, and thus never calling the LEAVE phaser.

    sub a() { END say "ended"; exit 1 };
    a   # ended

I don't think we're going to have an easy solution to that.  So yes, I think this is a trap that needs documenting.
