### ISSUE TITLE
RFE: Please add the following examples to routine +^

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/doc#3177]
Dear Raku,

On your doc page:
`https://docs.raku.org/routine/+$CIRCUMFLEX_ACCENT`

Would you please consider adding the following examples:

Under "multi sub prefix:<+^>(Any --> Int:D)" add
     For example:
       my uint8 $x = infix:<+^>( 0b1000_1010, 0b1010_0110 ); say $x.base(2)
      101100

Under multi sub infix:<+^>($a, $b --> Int:D)
     For example:
          my $v = 0b00001101 +^ 0b00001001; say $v.base(2);
         100

The above just makes it quicker to understand what is meant.  It also help those who have forgotten or do know what "infix" and "prefix" mean (beginners).  Keep in mind that those that already know what all this means DO NOT need to read this page.

Thank you for your considerations

**Comment by taboege** [comment]
> Under "multi sub prefix:<+^>(Any --> Int:D)" add
> For example:
> my uint8 $x = infix:<+^>( 0b1000_1010, 0b1010_0110 ); say $x.base(2)
> 101100

Why add an example using `&infix:<+^>` (without any comment?) to the documentation for `&prefix:<+^>`? That would surely confuse more than help.

> Keep in mind that those that already know what all this means DO NOT need to read this page.

I disagree. I know what all this is and from time to time I think I know how Raku works. Still, I sometimes need to consult the documentation about minutiae of signatures or edge cases or just to make sure this actually does what I expect it to do. Everyone needs to read this page at least once.

**Comment by ToddAndMargo** [comment]
On 2020-01-19 14:57, Tobias Boege wrote:
>     Under "multi sub prefix:<+^>(Any --> Int:D)" add
>     For example:
>     my uint8 $x = infix:<+^>( 0b1000_1010, 0b1010_0110 ); say $x.base(2)
>     101100
> 
> Why add an example using |&infix:<+^>| (without any comment?) to the 
> documentation for |&prefix:<+^>|? That would surely confuse more than help.

I am thick as a brick at times and it helped me.  I would love more 
explataion.  Do you have any suggestions?

>     Keep in mind that those that already know what all this means DO NOT
>     need to read this page.
> 
> I disagree. I know what all this is and from time to time I think I know 
> how Raku works. Still, I sometimes need to consult the documentation 
> about minutiae of signatures or edge cases or just to make sure this 
> actually does what I expect it to do. Everyone needs to read this page 
> at least once.

You make a good point.  I was trying to make sure the page
was written for both levels of skill.  Start small and work
up to complicated.

**Comment by JJ** [comment]
Again, I would prefer this to be a pull request. It allows to comment on the code, request changes and so on.

**Comment by taboege** [comment]
The construct `&base-name:<extended-name>` is standard Raku syntax for [extended identifiers](https://docs.raku.org/syntax/identifiers#Extended_identifiers). This entire string (except the sigil) is an identifier and, due to the sigil, names some Callable object, probably a subroutine.

Now, the `base-name`s `infix`, `prefix` and so on are special because the Raku parser takes all¹ its operators from such subroutines . Here, the `base-name` gives the *syntax category* of the operator and the `extended-name` gives the *operator symbol*. The parser sees if you declare a sub like this and adds to itself rules for parsing this operator symbol according to its syntax category. If you use Rakudo, the operators you normally use in your programs, like `infix:<+^>` are defined by the Rakudo developers in [exactly this way](https://github.com/rakudo/rakudo/blob/bd4b2c14873da334f102c00fa5bc01ee4e92d517/src/core.c/Int.pm6#L495).

If you say `infix:<+^>` then the syntax category of that operator is `infix`, so you **must** write the operator symbol `+^` between two terms (its operands): `$a +^ $b`. Alternatively, you can call this operator like a subroutine (because it is!) by using its **full name**: `infix:<+^>($a, $b)`.

This is different from `prefix:<+^>`! A prefix operator is unary, that is it has only one operand and the operator comes before it: `+^$a`. You can also call it as a subroutine, of course: `prefix:<+^>($a)`.

If you use the full name of an operator, you call it like any other sub. If you want to just use the operator symbol, you have to write it in the right place corresponding to its syntax category, so that the parser can pick up the right implementation of that operator. `$a +^ $b` will be compiled to use the infix operator `+^` on the operands `$a` and `$b`, whereas `+^($a, $b)` will be compiled to use the prefix operator `+^` on the operand `($a, $b)`.

I hope that makes it clear how the sub-calling syntax for `infix:<+^>` has no business in the documentation for `prefix:<+^>`. They are different operators as they are in different syntax categories. You apply them differently and they do different things. They just happen to share the same operator symbol.

Exercise for you: why do they share the same operator symbol? Find a relation between them. (If you want to solve it and write about it, that should probably be taken elsewhere.)

-------

Now, what to make out of this explanation in terms of this ticket? I think the right place to extend in this case is https://docs.raku.org/language/optut and maybe link to that here and there. All I said about operators is already on the pages I linked to and https://docs.raku.org/language/operators,
but maybe the tutorial can use more repetition. Will try to PR today.

-------

¹ "All" is a bit simplified. You will find mentions in the documentation that some operators are hardwired directly into the compiler and cannot be overloaded like this.

**Comment by JJ** [comment]
El lun., 20 ene. 2020 a las 10:26, Tobias Boege (<notifications@github.com>)
escribió:

> The construct &base-name:<extended-name> is standard Raku syntax for extended
> identifiers
> <https://docs.raku.org/syntax/identifiers#Extended_identifiers>. This
> entire string (except the sigil) is an identifier and, due to the sigil,
> names some Callable object, probably a subroutine.
>
> Now, the base-names infix, prefix and so on are special because the Raku
> parser takes all¹ its operators from such subroutines . Here, the
> base-name gives the *syntax category* of the operator and the
> extended-name gives the *operator symbol*. The parser sees if you declare
> a sub like this and adds to itself rules for parsing this operator symbol
> according to its syntax category. If you use Rakudo, the operators you
> normally use in your programs, like infix:<+^> are defined by the Rakudo
> developers in exactly this way
> <https://github.com/rakudo/rakudo/blob/bd4b2c14873da334f102c00fa5bc01ee4e92d517/src/core.c/Int.pm6#L495>
> .
>
> If you say infix:<+^> then the syntax category of that operator is infix,
> so you *must* write the operator symbol +^ between two terms (its
> operands): $a +^ $b. Alternatively, you can call this operator like a
> subroutine (because it is!) by using its *full name*: infix:<+^>($a, $b).
>
> This is different from prefix:<+^>! A prefix operator is unary, that is
> it has only one operand and the operator comes before it: +^$a. You can
> also call it as a subroutine, of course: prefix:<+^>($a).
>
> If you use the full name of an operator, you call it like any other sub.
> If you want to just use the operator symbol, you have to write it in the
> right place corresponding to its syntax category, so that the parser can
> pick up the right implementation of that operator. $a +^ $b will be
> compiled to use the infix operator +^ on the operands $a and $b, whereas +^($a,
> $b) will be compiled to use the prefix operator +^ on the operand ($a, $b)
> .
>
> I hope that makes it clear how the sub-calling syntax for infix:<+^> has
> no business in the documentation for prefix:<+^>. They are different
> operators as they are in different syntax categories. You apply them
> differently and they do different things. They just happen to share the
> same operator symbol.
>
> Exercise for you: why do they share the same operator symbol? Find a
> relation between them. (If you want to solve it and write about it, that
> should probably be taken elsewhere.)
> ------------------------------
>
> Now, what to make out of this explanation in terms of this ticket? I think
> the right place to extend in this case is
> https://docs.raku.org/language/optut and maybe link to that here and
> there. All I said about operators is already on the pages I linked to and
> https://docs.raku.org/language/operators,
> but maybe the tutorial can use more repetition. Will try to PR today.
>

Please, DRY. If you think something must be mentioned in several places,
just link to the canonical one, which is operators in this case.

**Comment by ToddAndMargo** [comment]
My great apologies, I got some of prefix and infix examples mixed up.  Sorry to 
have wasted so much of you guys time.  :’(

I have corrected the situation and, on the bright side, gives me a chance to add
some more examples.  

Since coercing  an unsigned integer can cause havoc at times (“leave my high bit 
alone!”), I believe it is necessary to also add how to work around the issue to save 
the user’s sanity.

Under 'Under "multi sub prefix:<+^>(Any --> Int:D)", should be:

> One's complement:
>
>     Note:
>             multi sub prefix:<+^>(Any --> Int:D) 
>     means that it will "coerce" your variable into an "Int".
> 
>       prefix:<+^>(0b1001);
>       -10   # got "coerced"
>
>        my $x =  +^0b1001.base(10)
>        -10   # got "coerced"
> 
>     Workarounds to the coercion:
>        my byte $x =  +^0b1001; say $x.base(2)
>        11110110
> 
>        constant WORD := uint16; my WORD $x =  +^0b1001; say $x.base(2)
>        1111111111110110
> 
>     my uint8 $x=0b1010_0110; 
>           my uint8 $y = +^$x; 
>           my uint8 $z = $y + 1;
>           say $x.base(2); say "0", $y.base(2); say "0", $z.base(2);
> 
>     10100110  # original
>     01011001  # one's complement
>     01011010  # two's complement


Under "multi sub infix:<+^>($a, $b --> Int:D)" should be:
> Exclusive OR (XOR)
>     my uint8 $x = infix:<+^>( 0b1000_1010, 0b1010_0110 ); say "00", $x.base(2);
>     00101100
> 
>      my $v = 0b00101101 ^ 0b00001001; say $v;
>      36   # 0010_0100
>
>      my $v = 0b00001101 +^ 0b00001001; say $v;
>     4    # 0000_0100
> 
>     my uint8 $x= 0b1000_1010 +^ 0b1010_0110; say "00", $x.base(2);
>     00101100
>
