### ISSUE TITLE
The documentation about the single argument role is confusing

### ISSUE THREAD

**Issue by chloekek** [Raku/doc#3268]
## The problem

I read the section _Single Argument Rule_ on the page _Lists, sequences, and arrays_ several times and it is still not clear to me what it is talking about. It talks about iterators, but that doesn’t seem to be referring to the Iterator role. It mentions iterative application out of nowhere. And then gives an example that seems completely sensible, as if it did not depend on any special “single argument rule” at all.

## Suggestions

Since I don’t understand what the section in question is trying to convey, I cannot make a concrete suggestion. But, it would be nice if it had two examples: one example that shows the behavior with the single argument rule, and one example that shows the would-be behavior in case there was no single argument rule.

**Comment by chloekek** [comment]
If I am correct, the syntax for _for_ statements is something like:

```
‘for’ <expression> <pointy-block>
```

When running it, expression should evaluate to a list. Then obviously, you can put a “single argument” there that evaluates to a list, such as a variable. But also a list literal, i.e. one with commas, since that is just another expression that evaluates to a list. So it seems like this documentation section is redundant.

**Comment by JJ** [comment]
It's the result of several issues, one closed (#600) and other still open #2368 . The bulk of the rule is explained somewhere else, but I guess we'll have to cross check against what you mention.

**Comment by uzluisf** [comment]
**Note:** More of this is taken from the sources listed below, only with minor rewording where I saw it fit.

---

In Raku, the single argument rule is the rule by which the set of arguments passed to an iterator (such as `for`) is treated as a **single argument** by the iterator, instead of **several arguments**. Thus, given some iterator `iter`,  `iter( a, b, c )` will *always* be treated as `iter( list(a, b, c) )` and *never* as `(iter(a))(b)...`. In the former case, the iterator is applied to the *whole single set* of arguments. In the latter case, the iterator is applied to the first argument, then the result from this iterative application is applied to the second argument, the result from previous iterative application is applied to the third argument and so on.

The single argument rule is best understood by considering the number of iterations that a `for` loop will do. The thing to iterate over is always treated as a *single argument* to the `for` loop, thus the name of the rule.

    for 1, 2, 3   { }       # List of 3 things; 3 iterations
    for (1, 2, 3) { }       # List of 3 things; 3 iterations
    for [1, 2, 3] { }       # Array of 3 things; 3 iterations
    for @a, @b    { }       # List of 2 things; 2 iterations
    for (@a,)     { }       # List of 1 thing; 1 iteration
    for (@a)      { }       # List of @a.elems things; @a.elems iterations
    for @a        { }       # List of @a.elems things; @a.elems iterations

The first two are equivalent because parentheses do not actually construct a list, but only group things. It is the `infix:<,>` operator that forms a list. By the rule, this means a list of three items is supplied to the `for` loop and this produces three iterations.

The third also performs three iterations, since in Raku `[...]` constructs an `Array` but does not wrap it into a `Scalar` container; each individual item is placed into a `Scalar` container though. By the rule, this means a list (an `Array` to be more precise) of three containerized items is supplied to the `for` loop and this produces three iterations.

The fourth will do two iterations, since the argument is a list of two things; these two things might have multiple  elements themselves, however they're still two things for the `for` loop. Notice how them having the `@`-sigil does not, alone, lead to any kind of flattening. 

As for the fifth, a single iteration is performed. This is because `infix:<,>` will happily form a list of one thing, even when that single thing might contain several elements; thus, for the `for` loop it's a single thing with multiple things in it. Contrast it with the sixth and seventh cases which perform `@a.elems` iterations because the `for` loop is supplied with a list of several things, instead of a list with a single thing (as in the fifth example).

The single argument rule does respect `Scalar` containers. Therefore:

    for $(1, 2, 3) { }      # List in a Scalar; 1 iteration
    for $[1, 2, 3] { }      # Array in a Scalar; 1 iteration
    for $@a { }             # Array in a Scalar; 1 iteration
All the above example perform a single iteration because regardless of how structurally complex the contents of `Scalar` container is, the container is a single thing.


Since what the iterator (in this case, the `for` loop) receives is a single argument, it will be treated as a list of elements to iterate over. The rule of thumb is that [if there's a comma, anything preceding it is an element](https://perl6advent.wordpress.com/2015/12/14/day-15-2015-the-year-of-the-great-list-refactor/) and the list thus created becomes the *single element*. As illustrated above, this is what happens with two `@`-sigiled variables separated by a comma (e.g., `for @a, @b {}`) or a single `@`-sigiled variable with a trailing comma (e.g., `for (@a,) {}`). In both cases, the iterator receives a single list. 

Sources:
* https://docs.raku.org/language/list#index-entry-Single_Argument_Rule
* https://perl6advent.wordpress.com/2015/12/14/day-15-2015-the-year-of-the-great-list-refactor/
* https://design.raku.org/S07.html#The_single_argument_rule

**Comment by uzluisf** [comment]
>It talks about iterators, but that doesn’t seem to be referring to the Iterator role.

The iterator is the object that returns a single value at a given time and then increments the internal pointer to the next value from an iterable. Flow control constructs such as the `for` loop are able to iterate through the data of iterable objects sequentially by calling the `iterator` method on the objects. Now the thing is that, unless you go looking for them, you won't find iterators explicitly in Raku due to them being hidden behind iteration APIs (e.g.,  the roles [Iterator](https://docs.raku.org/type/Iterator) and [Iterable](https://docs.raku.org/type/Iterable)).

 We know that the `for` loop implicitly calls the `iterator` method sequentially on its argument and `Iterator` objects are returned until the end has been reached. I think what's happening is that the documentation blurs the line between the construct for iteration (e.g., `for`) and the iterator (e.g., `Iterator` object). They're collectively called an iterator in the documentation.

A few months ago I created this gist about [Iteration, Iterables, and Iterators in Raku](https://gist.github.com/uzluisf/6faff852ace828a9d283d9aaa944e76d); you might find it helpful. Lizmat gave me a few important pointers, however I haven't reviewed/addressed further pointers since last time.

>one example that shows the behavior with the single argument rule, and one example that shows the would-be behavior in case there was no single argument rule.

From what I gather the simple argument rule is *always* present; whatever is supplied to the `for` loop, for example, is always treated as a single argument. Granted, that single element can contain many things, however it's still a single element.  Among other things, this is he kind of consistency that the Great List Refactoring (as mentioned in this [blog](https://perl6advent.wordpress.com/2015/12/14/day-15-2015-the-year-of-the-great-list-refactor/)) set out to achieve.

 This might be an oversimplification but thinking of whatever is passed to the *iterator* (blurring the line again) as a single list has helped me with the single argument rule. A good analogy might be of a single implicit outer box which is *always* supplied to the iterator. In some cases, the box might contain a list of things and the iterator iterate over those things. To be more precise, the box contains a single inner box that becomes the outer box; this is the case for `for a, b, c {}`, `for (a, b, c) {}`,  `for [a, b, c] {}`, `for @a {}`, etc. In other instances, the outer box contains several boxes and the iterator iterate over those boxes and not their contents; this is the case with `for ((a, b),) {}`, `for (a, b), (c, d) {}`, `for [a, b], [c, d] {}`, `for (@a,) {}`, `for @a, @b {}`, etc.
