### ISSUE TITLE
Where is the multi in starts-with?

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/doc#3456]
Dear Raku Developers,

https://docs.raku.org/routine/starts-with
multi method starts-with(Str:D: Str(Cool) $needle, :i(:$ignorecase), :m(:$ignoremark) --> Bool:D)

The above clearly states that it is a "multi method". But the page only shows one method. Where are the others? Am I missing something? Is this tagged as multi by accident?

-T

**Comment by JJ** [comment]
Let me see how I explain this. It's a bit like the American party primaries. Anyone can run, right? Only in some cases (mainly when the incumbent is there), nobody else bothers to. In this case, a [`multi`](https://docs.raku.org/syntax/multi) shows the possibility of declaring other routines with the same name and different signature, unlike [`only`](https://docs.raku.org/syntax/only) which says "Nope, you can't". 
As a matter of fact, there are [several of them](https://github.com/rakudo/rakudo/search?q=%22method+starts-with%22&unscoped_q=%22method+starts-with%22). However, in this case we made the call of putting them in a single definition, since the existence of different ones is simply an implementation detail.

**Comment by ToddAndMargo** [comment]
JJ,

Our documentation right now is incomplete, often inaccurate, and targets the wrong audience -- those who already know what they are doing and do not need the documentation.  Folks like you (experts).   Not folks like me (beginners).

If the documentation shows a "multi method", it is incomplete if you only show a single, easy one.  At the least, you show give a reference to the link you gave me if you don't feel like the effort of coping and pasting from that link you gave me.  

The documentation need to accurate and complete.  Shooting down fixed like this leaves the documentation is a miserable state.  Now we have a long way to go to get to the elegance of Perl 5's PerlDocs, but it must be our goal.   Leaving things incomplete is Anti-Kaisen (Anti Constant Improvement) and not helping in the least.

Raku is a wonderful example of a Kaisen project, as is Fedora.  Both keep getting better and better.  I am a YUGE fan of both.  Shooting down improvements in the documentation is a blemish in Raku's otherwise wonderful Kaisen process.

Please reopen and fix the issue stated.  You are a teacher.  You know how to do this.

Many thanks,
-T

**Comment by softmoth** [comment]
@ToddAndMargo, it sounds like you're suggesting that each `multi sub` or `multi method` listing only a single signature be a link to an explanation of [multi](https://docs.raku.org/syntax/multi).

You also seem to want all the implementation details to be shown in the documentation. I consider `multi` to be an implementation detail in many cases; if it can be *called* the same way, it doesn't matter if it is declared with several `multi`s or using optional arguments. It gets messy, since a routine might be `sub foo(|c) { dispatch-to-something(|c) }`, so we're always editorializing a bit to present a logical set of signatures to the user that describe how to call the routine. Different conforming Raku implementations could define routines in different ways.

And yet, sometimes those details matter. I probably don't need to know that there's `multi`s for `int32`, `int`, and `Int` in 12 different combinations for some routine. But sometimes I might really want to know if there's an optimized version or not. I think mentioning such details in an implementation-specific note in the docs is better than putting an extra list of signatures.

I think this could be explained somewhere in the docs. Maybe a `Language/documentation` that is mentioned in `Language/intro` or `Homepage`. There could be other conventions used in the documentation which could be explained to help readers interpret the docs correctly.

I can also imagine an optional view that shows all of the implementation details from a particular Raku compiler. This seems very hard to implement (probably involving annotating or parsing sources in rakudo, nqp (for Java, JS, , MoarVM), ...). Probably not useful for end users. Perhaps there's a way to meet somewhere in the middle.

Perhaps if you can provide even more specific suggestions about what you're wanting, it can keep the discussion moving forward. The question is not about being willing to put in the effort of copying and pasting or adding a link somewhere. Rather, there is not a clear good way to do what you are asking for, and "add a link" is not quite specific enough to act on.
