### ISSUE TITLE
Document "implementation-detail" trait

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3485]
Which does exactly as it implies, and is used [all over in Rakudo](https://github.com/rakudo/rakudo/search?q=implementation-detail&unscoped_q=implementation-detail). Check [some usage here](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-06-19#l73)

## Suggestions

Research what it actually does, and come up with useful examples that reveal real use cases.

**Comment by lizmat** [comment]
The `implementation-detail` trait is currently supported on subroutines and methods.  It basically sets a flag which can be introspected.  This flag is currently checked by introspection methods such as `.keys` on `PseudoStashes` and `.^methods` on classes.

Example: the CORE contains a subroutine `&DYNAMIC` that currently takes care of finding dynamic variables that haven't been found in the stack yet.

If you look for it directly, you will find it:

    say CORE::<&DYNAMIC>.raku
    # sub DYNAMIC (\name) { #`(Sub+{is-implementation-detail}|140341166976832) ... }

However, if you inspect `CORE::` with `.keys`, it won't show:

    dd CORE::.keys.grep( *.name eq "&DYNAMIC" )
    # ().Seq

That's because it's marked as an implementation detail.
