### ISSUE TITLE
Is Whatever (*) a term?

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3648]
## Problem or new feature

It's [documented as such](https://docs.raku.org/language/terms#term_*) in [this commit](https://github.com/Raku/doc/commit/7920acd3e954c2a8e43c7d6c28df8293ba00914f) added 6 years ago.

## Suggestions

Not entirely clear we can call it a term in the sense others like now or pi are, these are [defined below](https://docs.raku.org/language/terms#Identifier_terms). It does [not seem to be defined that way in Rakudo](https://github.com/rakudo/rakudo/search?q=%22sub+term%22&type=code), either.

It should probably be removed from the page, or at any rate moved to another section.

**Comment by pmichaud** [comment]
```Whatever``` is grammatically defined as a term in Rakudo at https://github.com/rakudo/rakudo/blob/86bac5ad59890806dc2e99b4ef0544f47670d310/src/Perl6/Grammar.nqp#L1503 .  

```    token term:sym<*>                  { <sym> } ```

There are a lot of other terms defined there as well.

Pm

**Comment by JJ** [comment]
Still, that's a tutorial-level document, which probably should not make any reference to the implementation. It would probably be the best to just skip "term" there, or else move it below to the "identifier terms" subsection.

**Comment by pmichaud** [comment]
Okay, I will rephrase a bit.  Whatever (*) is definitely considered a term in Raku, and is implemented that way in Rakudo.  In concept, design, and implementation, it's always been a term.  I find it hard to think of it as being anything else.   In nearly every common example I can think of involving Whatever (*), it's a term.

I don't know that I would classify it as an "identifier term", because it doesn't follow the rules for identifiers.  It definitely acts more like the other literal terms such as numeric constants, lists, regexes, etc.

I guess I don't understand the confusion or reason why Whatever (*) /shouldn't/ be listed among the other terms on this page, ir where it could be more properly documented.

Pm

**Comment by JJ** [comment]
The problem is not what it *is* but what we *call* it in *this specific page*. I've tried to clarify it a bit, and left it in the "literals" section. Please feel free to rewrite, revert or clarify it further.
As a matter of fact, it its very own page the phrase "in *term* position" is used. So, anyway, I've tried to be a bit informative in the explanation, and just eliminated its "term" description, which in a way is implicit since it's the Terms page anyway.
