### ISSUE TITLE
Command line parameters are not documented (including -ll-exception and -I)

### ISSUE THREAD

**Issue by lizmat** [Raku/doc#3718]
## Problem or new feature

The -I command line parameter, for including a directory into module searches, does not appear to be documented

## Suggestions

It probably should be documented.

**Comment by JJ** [comment]
If I remember correctly, this was actually delegated to Rakudo because, you know, it's not a language but an implementation issue. I wonder if it still makes sense. We have an entry for [environment variables here](https://docs.raku.org/programs.html), but not for command line arguments. Anyway, that's where it should go.

**Comment by JJ** [comment]
I've found this issue #1668. Let me see if I find where we said "it was going to Rakudo"

**Comment by JJ** [comment]
And now everything is coming back to me, including this issue #949 that was the origin of the removal, to which I (more or less vehemently) opposed.

**Comment by JJ** [comment]
The [wiki page it's been moved to](https://github.com/rakudo/rakudo/wiki/Running-rakudo-from-the-command-line) hasn't changed since it was created. I'm not sure the command line has evolved since then, it probably has.

**Comment by coke** [comment]
We should document any of the compiler args that are in Roast, which include at least -I, -n, -e, -p, --doc, and close out with a link to rakudo's wiki page for any non-standard ones.

**Comment by cfa** [comment]
There seems to be fairly comprehensive switch documentation [here](https://docs.raku.org/programs/04-running-raku).
