### ISSUE TITLE
Pencil symbol links to a 404 on Github

### ISSUE THREAD

**Issue by lizmat** [Raku/doc#3753]
As mentioned on the mailing list.

At least this page:  https://docs.raku.org/language/syntax  links to something that does not exist as such on Github.

**Comment by JJ** [comment]
Noted and created as  Raku/documentable#146. Will try to fix it now.

**Comment by JJ** [comment]
A fix has been deployed to the [staging site](https://rakudocs.github.io/), for the time being. Give it a test ride and I'll close this everything seems OK. BTW, it now points to the page, not to the link that edits the page. That's a small change that might avoid confusion in case the person does not have permission, and saves some clicking in case you do, because in most times you won't really want to edit it (I use it simply to get to the page itself). It's probably better if it goes back to the original link, anyway, which jumped directly into the editor.
