### ISSUE TITLE
built-in compound assignment operators like "~=" are not searchable

### ISSUE THREAD

**Issue by bazzaar** [Raku/doc#3768]
## Problem

Common built-in compound assignment operators like  +=, -=, *=, /=, min=, and ~= are not searchable

## Suggestions

Perhaps provide a separate sub-section on their use, in the "Assignment Operators" section, starting with simple use cases, more technical details could follow that. Also perhaps provide an example of ~= usage, in the "String Concatenation Operator" section.

**Comment by JJ** [comment]
The problem is that there's a huge amount of different combinations that can be generated; I don't think it's feasible to index all of them. We can provide some examples, though.

**Comment by JJ** [comment]
It looks like [the section on metaoperators](https://docs.raku.org/language/operators#Metaoperators), that says they're coming up next, has somehow disappeared...

**Comment by bazzaar** [comment]
The thing with these compound assignment operators is, ... the assignment part isn't the most interesting bit from the user perspective. I just wanted to find out if using the tilde before the equals was a recommended way to concatenate one string to another existing string. So it seems to me that if there is a section on the concatenation operator, then it should automatically show a compound assignment use case.

**Comment by JJ** [comment]
The problem is deciding which ones of those are important enough to deserve their own example since, in principle, you can mix any infix operator with `=` to create a metaop; you can even *infixizy* (yes, that's a word, I made it up) a 2-arg op and create an assignment meta-op. I concur that more examples, with real use cases, is always better than few examples, so adding an example here is not a problem. The "like" part of your issue is, since you are actually asking to make searchable quite a lot of combinations of operators, something that's not really feasible.

**Comment by bazzaar** [comment]
so if I search for "~" and don't find "~=" in the suggested links, then that to me is lta. Could a "generic suggestion link" shown as "~=" be automatically tacked onto the end of the list of actual links, that would point at compound assignment and give the user a starting point? Just wondering.

**Comment by bazzaar** [comment]
Apologies, I didn't see the existing issue on this topic, I will close this issue and defer to the other.
