### ISSUE TITLE
"shift" example is non-idiomatic raku

### ISSUE THREAD

**Issue by fecundf** [Raku/doc#3822]
## Problem or new feature

The first example for `shift` [its doc page](https://docs.raku.org/routine/shift) shows a while loop that is a little dangerous:

```
while my $value = shift @foo {
    say $value;
}
```

It's not a good use of "shift" and it's non-idiomatic Raku for looping over Iterable. What if `@foo` contained `0, False, Any`?

## Suggestions

Change example to along these lines-

```
my @queue=<1st 2nd 3rd>;
my $head = shift @queue; # $head is now '1st'
@queue.say; # [2nd 3rd]
```

**Comment by JJ** [comment]
I'm not totally sure about calling something idiomatic, when TIMTOWDI. Good or bad uses are, at the end of the day, a judgment call. What's being exemplified is that shift returns a value; if @foo contains 0, maybe the original user wants it to indicate end of loop... There are also many ways to loop over Iterable: for is one, but there is also `map` or hypers.
You have a point that maybe we should point out more clearly what it does, but this being about shift, not about Iterables, I don't see how one thing would be better (or "idiomatic") while others would not.

**Comment by pmichaud** [comment]
Oh, Raku definitely has idioms, or at least was designed with idioms in mind.  While we often refer to TMTOWDI, the longer Raku version was "TMTOWTDIBSCINABTE", which is "There's More Than One Way To Do It, But Sometimes Consistency Is Not A Bad Thing Either".

We often discussed that there ought to be a really good "standard" and "obvious" ways of doing things, but the idiomatic way should not have to be the only way to do something.

In the specific example involving 'shift', I agree with OP that this isn't the example that would come to my mind when trying to describe what shift does, because it can have unexpected outcomes for a newcomer, and the syntax is a little confusing besides.  (Is the block somehow part of the 'shift' keyword?)

I like the proposed example in this issue, or perhaps even better would be to use the same example given for (Array) method shift that follows on the documentation page, but using the routine version instead of the method one:

    my @foo = <a b>;
    say shift @foo;             # OUTPUT: «a␤» 
    say shift @foo;             # OUTPUT: «b␤» 
    say shift @foo;
    CATCH { default { put .^name, ': ', .Str } };
    # OUTPUT: «X::Cannot::Empty: Cannot shift from an empty Array␤»

That might also help reinforce the routine-versus-method way of doing things.

My $0.02,

Pm

**Comment by JJ** [comment]
There are not many rules about examples; one of them is #1748. Besides, you're mainly questioning its use in a loop, which is not the object of the example; it's the use of `shift` and I don't see any problem in that. However, I *do* see a problem in hiding that shift over an empty array fails, and we're hiding that fact.
So, related to #1748, let me see if I can find a good use case for shift that's, at the same time, does not hide results under the table.

**Comment by JJ** [comment]
Additionally, although it looks like we're applying shift on List, @-sigilled containers by default are Arrays, not Lists. So there's something else to worry about there... Working on it anyway now.
