### ISSUE TITLE
Should the ternary operator be moved from "Operators" to "Control flow"?

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3914]
We currently document the ternary operator on the [Operators page](https://docs.raku.org/language/operators#infix_??_!!) as `infix ?? !!`.  But it doesn't really seem to be an operator at all (in the way Raku uses the term, anyway), and it _really_ doesn't seem to be an infix operator.  In the [operator classification section](https://docs.raku.org/language/operators#Operator_classification), we say that infix operators – actually, all types of Raku operators – take just two arguments.  `?? !!` isn't implemented as an operator, and it isn't possible for a user-defined operator to behave like `?? !!`.  

Compare how we treat other conditionals: we document `infix:<and>` as an operator – which makes perfect sense; it's implemented as one.  But we don't document `if` as an operator, even though `(2 > 1) and 42` is very similar to `(if 2 > 1 { 42 })`.  Instead, we have `if` on the control-flow page.

It seems to me that we should do the same thing with the ternary operator (perhaps with a reference from the operator page, since it's an "operator" in the colloquial sense, even if not in the Raku sense).  But I wanted to see if others agreed before making the change.  Another option would be to document `?? !!` as `ternary ?? !!` instead of `infix ?? !!`, but that strikes me as more confusing than moving it).

The current `?? !!` documentation hasn't been substantively changed since it was added in 2012 in cb36b25010457070aeb7e4eed5ed162d4245f9f3; that commit added docs for several other operators and didn't mention `?? !!` in its commit message.

**Comment by Altai-man** [comment]
Sadly, I am against any changes of such sort to the documentation due to absence of proper versioning of pages, leading to broken URLs whenever any tiny bit like this one gets edited or deleted.

**Comment by JJ** [comment]
@Altai-man a bug is a bug; and what @codesections says makes sense. We can change internal links, and check it there's any external one.

**Comment by Altai-man** [comment]
>We can change internal links, and check it there's any external one.

You will never know if there are any external links you just cannot find. And if you can, finding them won't help either.

**Comment by codesections** [comment]
I guess a good compromise would be to leave a `?? !!` section in Operators, but mention that it's not an operator in the Raku sense and link to the new section on the Control Flow page.  That wouldn't break any links, but would still clear it up.

I'll try to put a PR together along those lines.

**Comment by lizmat** [comment]
Maybe also note that, at least currently, `||` and `&&` are no real operators either in the Raku sense, since they can shortcut.  We have no way to indicate in a signature that the second argument of a sub should only be evaluated if the first one is `True` (in the case of `&&`) or `False` (in the case of `||`).

Yes, `&infix:<||>` and `&infix:<&&>` return something, but that's just for introspection uses, afaik.

**Comment by codesections** [comment]
>  We have no way to indicate in a signature that the second argument of a sub should only be evaluated if the first one is ` True` (in the case of `&&`) or `False` (in the case of `||` ).

We don't?  I thought the following would provide that behavior:

```raku
sub custom-or(|c) { if c[0]() -> $first { $first } else { c[1]() };
```

Am I misunderstanding something?

**Comment by codesections** [comment]
That made sense when you said it, but I actually tried it out and it still seems to work fine:

```

multi infix:<❚❚>(|c0, |c1) { 
    do if c0[0] ~~ Code {
        if c0[0]() -> $first { $first  } 
        elsif c1[0] ~~ Code  { c1[0]() }
        else                 { c1      }}
    else {
        if c0[0]   -> $first { $first  } 
        elsif c1[0] ~~ Code  { c1[0]() }
        else                 { c1      }}}

say 42 ❚❚ Proxy.new(:FETCH(method () {die "oops"}), :STORE);
say { 'also works' } ❚❚ { Proxy.new(:FETCH(method () {die "oops"}), :STORE) }
```
[tio link](https://tio.run/##vZAxCsJAFET7nGIQwQSiRBGLKDai2ClqJxYh2eBidCUbUVnXgwhezovEn0RFtLJx2GL4//1h2C2Lo1aaGutdlHDwTcgPbud2vdDrmiffsXHy6xYUDJACAR7Cd@bOAuczeiJgUPkm03NlWqh2UQ55LBO6fBhovEgWyQyuv@cQmQ/oWr@DDJ/KwMLpgsyp7x5k/9ZDG4b0jmg2UHwexrE4HGsbtjfdQX/WG5prlixFAIpVAWcoCbGVJW3ZcKez0aRvtfMAhYoXSYG9iFeyQl0fcer3QKqfpnc)

**Comment by lizmat** [comment]
I think that should be a compilation error, because this does not do what you think it does:
````raku
sub a(|c0,|c1) { dd c0, c1 }; a 42, 666
# \(42, 666)
# \(42, 666)
````
Aka, both captures refer to the same thing: all parameters.

**Comment by lizmat** [comment]
I was more thinking along the lines of:

````raku
my $a := Proxy.new(:FETCH(method () {die "oops"}), :STORE);
sub foo($b) { }
foo $a;   # oops
````

**Comment by codesections** [comment]
> this does not do what you think it does.  Aka, both captures refer to the same thing: all parameters.

Oops!  Good to know, thanks :grin:  But still, that doesn't change the example that much – really, just simplifies it.

> I was more thinking along the lines of [code with `sub foo($b) { }`]

Yeah, I understand that that dies.  But in terms of whether we need to document that `&infix:<||>` is special and has short-circuiting behavior not available to user code… it seems like user code _can_ implement short-circuiting operators.  They have to jump through hoops because the aren't allowed to have a signature that binds; but if they stick to `|c` and test everything before evaluating too much, it looks like userspace operators can short circuit.

Unless I'm still missing something – as I showed with `(|c0, |c1)`, that's entirely possible!

**Comment by pmichaud** [comment]
On Mon, Jul 12, 2021 at 12:12:11PM -0700, Daniel Sockwell wrote:
> Yeah, I understand that that dies.  But in terms of whether we need 
> to document that `&infix:<||>` is special and has short-circuiting 
> behavior not available to user code… it seems like user code _can_ 
> implement short-circuiting operators.  

(Historical notes)

If I remember correctly, in the earlier days of Raku/Perl 6 development, 
short-circuiting behaviors were relegated to the realm of macros and/or
AST tree modification sorts of constructs, as opposed to the standard
functional/operator syntax.  We looked at making a variety of thunk-like
behaviors fit into the function call syntax, but it never worked.  As
a result the short-circuiting operators have always had some special 
handling in the compiler.

It's also worth noting that for a long time (I don't know the current
state of things), conditional statements and short-circuiting operators
were generally represented in the AST as the same node types.

Personally, I'd keep the short-circuit operators remaining documented
as operators, including the ternary.  A loose differentiation of "operator"
from "statement" is that operators are often used for their return
value, whereas statements are less likely to have that happen.

Pm

**Comment by codesections** [comment]
> Personally, I'd keep the short-circuit operators remaining documented
as operators, including the ternary.  A loose differentiation of "operator"
from "statement" is that operators are often used for their return
value, whereas statements are less likely to have that happen.

That makes sense, thanks!  Under that logic, maybe we should also mention [do](https://docs.raku.org/language/control#index-entry-control_flow_do-do) on the Operator's page – under the "loose definition" you mentioned, `do` can be thought of as a prefix operator that turns a statement into an expression.

Thinking through the points @pmichaud and @lizmat raised, I wonder if we should have a "special case operators" section of the operators page that notes operators that don't fit in the [6 operator categories](https://docs.raku.org/language/operators#Operator_classification) of that we currently list, (pre|in|post|circum|postcircum|method)fix.

That section would include both `?? !!` (currently incorrectly documented as being in the `infix` category) and `s///`/`t///` (currently documented without listing a category but also without noting that they're an exception)

**Comment by codesections** [comment]
Closing in favor of #4033, which more squarely frames the problem as about distinguishing between types of operators rather than determining which operators are "real" operators.

**Comment by 2colours** [comment]
> Yeah, I understand that that dies. But in terms of whether we need to document that `&infix:<||>` is special and has short-circuiting behavior not available to user code… it seems like user code _can_ implement short-circuiting operators.

@codesections I think this was enough of an eyebrow-raiser that it shouldn't have gone unnoticed. Indeed, if it's this simple to implement short-circuiting, why did the core not take benefit of this?

Turns out it's because it's **not** this simple, and I wish this didn't go unnoticed back then because this is a very interesting topic.

Let me ignore the second example because the very point was to avoid having to wrap expressions into `Callable` objects. Now, the problem immediately becomes apparent if you have a non-shortcircuiting expression on the right handside, say, `(1, Proxy.new(:FETCH(method () {die "oops"})`. None of that should be evaluated, yet it dies with your custom operator.

If I were to guess, it was just a "lucky coincidence" that Proxy.new itself is probably lazy in the same sense a Seq is lazy; it can be passed around without retrieving the value. Now you are forced to resort to operations that deal with it without actually evaluating them - if they can manage at all. Worse yet: what if you simply have a subroutine with a side-effect on the right handside, how are you gonna postpone that?

The point is, both sides will be *evaluated*. What the result of the evaluation is a different story but you can barely control it.

This is where "thunky operators" come into play: for aesthetic pleasure, they utilize something that isn't a first-order part of the language: expressions. In the "old frontend", this really means they are parsed in a way that they receive and utilize the produced QAST on one side, intercepting its evaluation depending on the circumstances, thereby really doing something that control statements do...

Currently, even if you call `&infix:<&&>`, you **cannot** get this behavior; only by EVALing something that contains the operator syntactically. I think RakuAST _could_ mitigate this but that would require focused work into that direction (currently, "thunkiness" seems a bit ad-hoc in RakuAST; sometimes it's hardcoded into the tree, sometimes it isn't).
