### ISSUE TITLE
Py-nutshell: enumerate()

### ISSUE THREAD

**Issue by mykhal** [Raku/doc#3924]
[Py-nutshell](https://docs.raku.org/language/py-nutshell) doc is lacking known and useful Python `enumerate()`.

Proposal stub:

> ### Enumerate()
> 
> Python
> ```python
> elems = ["aether", "hydrogen", "helium", "lithium"]
> for i, e in enumerate(elems):
>     print "elem no. %d is %s" % (i, e)
> # elem no. 0 is aether
> # elem no. 1 is hydrogen
> # ...
> ```
> 
> Raku
> ```raku
> my $elems = <aether hydrogen helium lithium>; 
> for $elems.kv -> $i, $e { say "elem no. $i is $e" };
> ```

I'm using conservative Python syntax, as current doc examples are in Python 2.  
Also not sure if there's some other more idiomatic Raku way.

**Comment by treyharris** [comment]
My PR doesn’t quite match your example because I thought it would be a good idea to show that `.kv` replaces both Python’s `enumerate()` and `items()`. Also, I didn’t think there was any reason to use `$`-sigil variables for the containers (but, if you had a particular reason to do it that way, please say so).

Finally, the imaginary zero-atomic-number element isn’t “aether”, but “neutronium” (with, oddly, lowercase **n** as its chemical symbol). ;-)

**Comment by mykhal** [comment]
I've seen that "neutronium" too, it's somewhat more complicated than Wikipedia articles, i'd still prefer classical *aether*, it's not (history of) science textbook.
