### ISSUE TITLE
`OUTPUT: «…␤»` for exact vs `OUTPUT eg: «…␤»` for example/random outputs

### ISSUE THREAD

**Issue by mykhal** [Raku/doc#3927]
In most cases of doc code examples, the `OUTPUT: «…␤»` is deterministic and is sort of a test case.

In some cases (e.g. when containg `rand`, `.pick`, `.roll`, `.WHERE`, `now`, …) the output is non-deterministic. It might not be always obvious for everybody.

It would be helpful to denote these in a different way, e.g. `OUTPUT ex.:`  
(I can't see a Unicode symbol for *example*.)

**Comment by JJ** [comment]
Pretty good idea. Thanks!

**Comment by mykhal** [comment]
@raiph English tongue is not my native one, I guess that "eg" is better *example* abbr. than "ex".

**Comment by JJ** [comment]
Well, if we're going to get all academic, e.g. (exempli gratia) would the the better substitute for ex (example) which looks good to me anyway...

**Comment by JJ** [comment]
Well it's got its origin in the responses by the Camelia bot in IRC. The original authors (and myself) used it to cut and paste responses.
Anyway, the OP seems quite reasonable: just clarify that YMMV. And you're correct, featuring the right feature will force us to be minimalistic in the code, and thus to show that the output might vary.
At the end of the day, since we are in Hacktoberfest, I'd happily accept a PR that would hightlight variable output with `e.g.` or some other way of making that clear.

**Comment by coke** [comment]
I'm leaning towards **both** "we don't need to be this specific and note variable output" **and** "we don't need to be this specific and show the newline character"

**Comment by coke** [comment]
Rejecting the "e.g." adding to the output, but I appreciate the suggestion.

Regarding the presence of ␤ or not in the output, that is tracked under #2670
