### ISSUE TITLE
Update new CPAN policies

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3998]
## Problem or new feature

CPAN is no longer the preferred way of distributing modules, as affirmed [here](https://docs.raku.org/language/modules#Upload_your_module_to_CPAN). It's discouraged, even.

## Suggestions

Change that to the Raku ecosystem, improving if possible instructions on how to use [fez](https://github.com/tony-o/raku-fez)

Additionally, just review the whole section, which still encourages Travis.

**Comment by jonathanstowe** [comment]
> It's discouraged, even

I just love how these things get decided without any attempt at consultation with people who actually have a stake in the matter.

**Comment by JJ** [comment]
Sorry, @jonathanstowe but there's a long story of [CPAN being a problem](https://github.com/Raku/problem-solving/issues?q=is%3Aissue+is%3Aopen+cpan), including the fact that what's in there is not even tested. Now that we have a fez ecosystem in place, it's better to start moving there as soon as possible. It's also in the [RSC minutes](https://github.com/Raku/Raku-Steering-Council/blob/69f10bbea0d72fef35df2a7b95ad3857e49a9bd4/minutes/20211002.md). I'm sorry to hear that, and we're obviously happy to hear anyone with a stake in the subject.

**Comment by jonathanstowe** [comment]
I have [a lot of modules](https://modules.raku.org/search/?q=author%3A%22JSTOWE%22) - it took me several months to move them all to CPAN from the GH ecosystem when that was deprecated, several months to `s/perl6/raku/g` and so and so forth and I've not yet caught up on the META6 changes, all the while adding new stuff to the ecosystem which somewhat conforms to the state of play at that time.  I don't have sufficient time to keep abreast of every possible stream of discussion and decision making.

What concerns me is that, as soon as it is suggested that the CPAN ecosystem is discouraged or deprecated in the documentation, some well-meaning but over-enthusiastic person is almost inevitably going to raise GH issues on all my modules that I should move them all to the new hotness, and worse, probably automate the creation of those issues. This will almost inevitably annoy me and probably upset the person when I bulk close the issues with a terse note.

FWIW I'm not actually arguing against recommending `fez` rather than CPAN: I'm totally aware of the advantages of `fez` and the shortcomings of CPAN and _at some point_ I plan to move the stuff across, it's just time consuming and sometimes, y'know, actually making software is of higher priority than tinkering around with the means of distribution of that software.

**Comment by lizmat** [comment]
FWIW, I'm planning to move all of the raku-community modules to zef.  Would PR's help you in moving to zef ?

**Comment by jonathanstowe** [comment]
It's more a matter of re-jigging my tools and workflow then devising some means of moving the whole lot in one go in as automated a fashion as possible, so I don't have to touch them all by hand.  On the face of it none of this seems particularly intractable, I've just got to examine how `fez` works so I can tailor it to my thing.

**Comment by lizmat** [comment]
A headsup on the raku-community-modules situation.  `App::Mi6` has a PR for supporting fez groups, and with that I was able to upload the `Die` and `Slang::Roman` distrbutions to zef.

For the moment I'm still the only person in the zef `raku-community-modules` group.  Please let me know your zef name and I will add you to that group.  If you want to be able to upload raku-community-modules to zef of course :-)

What I also did (and intend to do for basically all non-archived raku-community-modules, is to:

- switch the default branch to "main"
- update file extensions
- add my custom "run-tests" and .github/workflows/test.yml for CI
- make the distribution compatible with `App::Mi6`

This would mean that future maintainers would only need to do:
- code changes, update of documentation and Changes info and update testing
- run "mi6 release"

**Comment by tbrowder** [comment]
On Wed, Dec 22, 2021 at 07:22 Elizabeth Mattijsen ***@***.***>
wrote:

> For the moment I'm still the only person in the zef raku-community-modules
> group. Please let me know your zef name and I will add you to that group.
> If you want to be able to upload raku-community-modules to zef of course :-)
>
     zef:tbrowder

Thanks.

-Tom

**Comment by JJ** [comment]
zef:jjmerelo

**Comment by lizmat** [comment]
@JJ @tbrowder invites sent!

**Comment by sdondley** [comment]
I submitted a patch for this 8 days ago: https://github.com/Raku/doc/pull/4008

Seems I screwed up and overwrote it when merging a branch.

**Comment by sdondley** [comment]
OK, recovered the PR. Now at #4013

**Comment by coke** [comment]
re-ordered so fez is first. linked to the fez repo which has usage instructions of its own.
