### ISSUE TITLE
xt/examples-compilation.t doc/Language/containers.pod6

### ISSUE THREAD

**Issue by coke** [Raku/doc#4020]
from

```$ xt/examples-compilation.t doc/Language/containers.pod6```

```
   # my Int \z = 42;
    # z := 100; # OK
    # z := "x"; # Typecheck failure
    # Cannot bind to 'z' because it is a term and terms cannot be rebound
    not ok 4 - doc/Language/containers.pod6 chunk 4 starts with “my Int \z” compiles
```

This example is not currently correct  and dies on the first bind:

```
23:43 < [Coke]> m: my Int \z = 42; z :=100;
23:43 < camelia> rakudo-moar 284b56232: OUTPUT: «===SORRY!=== Error while compiling <tmp>␤Cannot bind to 'z' because it
                 is a term and terms cannot be rebound␤at <tmp>:1␤------> my Int \z = 42; z :=100⏏;␤»
```

Bisectable6 output: https://gist.github.com/Whateverable/6f770a2858b5477de41b1581e4e067e6

Shows a change in behavior, but this may have never worked as intended. The example needs to be improved (and if it isn't intended to compile, should skip the compilation test.

Also check the other code that has the comment "Typecheck failure" as it is not failing - the example there is compiling and doesn't look like it intended to.

This code hasn't change in some time in the file.

**Comment by codesections** [comment]
Oh, that must be from my Rakudo PR from a bit before that release (rakudo/rakudo#4536).  I'll take a look at this – from a quick glance, it looks like we were documenting a bug as though it was intentional.  Oops!

(Though, in fairness, it took quite a while – and quite a few SO questions – to figure out which rebindings were supposed to be allowed, so I'm not surprised that our docs didn't always get it right.  With that PR merged, I really ought to get back to #3961 and make sure we have all the rules in one place in the docs)
