### ISSUE TITLE
Remove 'Defined as:'

### ISSUE THREAD

**Issue by coke** [Raku/doc#4134]
Looks like there was a style at some point to use

``
Defined as:
``

at the top of a routine before the method signature. I think this is unnecessary and we can just lead with the method declaration.

**Comment by coke** [comment]
Another ticket mentioned Declared as, which had only one use and was recently removed.

**Comment by 2colours** [comment]
@coke could you show the ticket with "Declared as"?

I don't feel strongly about this one, either "for" or "against". Perhaps it could go but again, it would be good to get opinions from others who might be interested. @0rir what do you think, for example?

**Comment by 0rir** [comment]
I didn't find the issue mentioning it, so my opinion is tentative.

As documentation, I think it can go as non-informative.  And it is optional in `xt/check-signatures.t` 's `grammar TypeDocumentation`.  That suggests it is just a waste of space.

**Comment by coke** [comment]
#3441

**Comment by 2colours** [comment]
I'm trying to somewhat assure it doesn't hit anyone as a big surprise but otherwise I think the situation is in favor of the removal. It could even be removed from the tests and then we could quickly see where there are left-behinds.

**Comment by 0rir** [comment]
Thanks, @coke, I guess I messed up with the quoting to find #3441.

There are roughly a thousand instances all, or nearly all, under `/types`.  Reading through #3441, my opinion is affirmatively that those should go.

I won't volunteer because I have not dealt with any Not-Invented-By-Me grammars  and feel my match object to action class tooling is weak.   And, I feel like I should continue work on Issue #4117, even without feedback on my plan.   (@Altai-man, is silence consent or lack of time.)

**Comment by Altai-man** [comment]
> I won't volunteer because I have not dealt with any Not-Invented-By-Me grammars  and feel my match object to action class tooling is weak.   And, I feel like I should continue work on Issue #4117, even without feedback on my plan.   (@Altai-man, is silence consent or lack of time.)

It is lack of time mostly, due to dayjob. If you can suggest a PR for improvements to categories noted - we should have it, it will be a help.
