### ISSUE TITLE
Let's provide a link to roast for every documented feature!

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#836]
… I know it sounds scary, but wouldn't it be amazing?

Besides providing some extra examples and making stuff more clear in places where the documentation is not that great, it will also give us an easy way to find undertested features!

I think that it is a great idea, at least hypothetically. Now how do we implement this? Line numbers in roast are not permanent. Does it mean that we will have to put some kind of special markers in roast files?

**Comment by gfldex** [comment]
Str::match (that is not documented, that's why I know) shows up in 12 different spec files. There are many such features. If you look for subscripts it's dozens of files.

The idea sounds appealing until you try to implement it. It's just way to much stuff to handle. If you want to find stuff in the spec you have to have good grep skills.

**Comment by pmichaud** [comment]
I think piggy backing off the existing markers is a good idea, and it's also a reasonable way to add new markers into roast.

I also think that if one doesn't try to be exhaustive about it -- i.e., accept that some documentation pages might not have all (or any) of the relevant references to roast -- it can still be very useful to have.  For example, with Str::match it might be okay to simply link to a few prominent instances of Str::match being used in roast, rather than try to find and link all of them.  If someone needs to know all of the occurrences, then do a grep.  :)

Pm

**Comment by JJ** [comment]
Should this be part of the documentation, or part of the site? Like, try and link every Type to a roast test file.

**Comment by AlexDaniel** [comment]
@JJ I think this can only be done section by section, so it'd need **a lot** of work and yes, it should be part of the documentation.

**Comment by stmuk** [comment]
I wouldn't agree that the docs in this repo are intended for entry (level?) users. It's mostly reference type documentation which is generally read by more experienced users. Entry level users are probably better off reading tutorial type documentation (which is sadly lacking at the moment) as a primary resource and using reference documentation as a secondary resource (until they become more used to it).

I think the original idea of linking ref docs to roast tests is a excellent one and the original issue should be kept open.

**Comment by AlexDaniel** [comment]
> Issues are better solved than kept open

Yes but closing a github issue does not solve the issue.

> to a GitHub search query in the roast repo can be easily done

I don't think it'll give any meaningful (or usable) results.

> Advanced users can probably figure out looking stuff up in roast without us taking them by the hand.

That's LTA.

**Comment by AlexDaniel** [comment]
[Less Than Awesome](https://docs.perl6.org/language/glossary#LTA).

> if solving this issue involves reviewing every single doc page and adding something, as well as adding something else to the build system, I'd really rather not

Well… you don't have to do it…

**Comment by JJ** [comment]
So that's what you are looking for? Including some tag or metadata in every page indicating the corresponding roast test? Anything less than that would be LTA?

**Comment by JJ** [comment]
Also, we could try to figure out the link Class name → synopsis → roast line numbers that has been mentioned above. I don't know how hard it would be or how generalized are these markers. But hoping that they are good for every class here is a long shot.
I still think that in this case the best would be to arrive to a compromise option, like including that in the writing guide and make it more or less compulsory for every class file that is modified, maybe by including an author test.

**Comment by coke** [comment]
I think we'd need to spend the time first in cleaning up roast so that it is clear what feature is being tested, at which point, we can use the information from tagging in roast to drive the documentation links. I don't think having this in raku/doc *first* makes sense. If someone is still exciting about this, please open a roast or problem-solving ticket to track this issue. Thanks.
